learnapp/urls.py
from django.conf.urls import url
from learnapp import views
app_name= "learnapp"
urlpatterns=[
 url(r'^details/$',views.details, name = 'details'),
]

learntemps/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from learnapp import views

urlpatterns = [
    url(r'^learnapp/',include('learnapp.urls')),
    url(r'^$',views.index, name= 'index'),
    url(r'^admin/', admin.site.urls)
]

learnapp/models.py
from django.db import models

class info(models.Model):
    name= models.CharField(max_length=250,unique='True')
    details= models.TextField();

    def __str__(self):
        return self.name

class webs(models.Model):
    namew= models.ForeignKey(info)
    webpage = models.URLField(unique='True')
    email = models.EmailField()
    def __str__(self):
        return self.namew




# Create your models here.

learnapp/forms.py
from django import forms
from learnapp.models import info,webs

class fm1(forms.ModelForm):

    class Meta():
        model = info
        fields = '__all__'

class fm2(forms.ModelForm):

    class Meta():
        model = webs
        fields = '__all__'

learnapp/views.py
from django.shortcuts import render
from learnapp.forms import fm1,fm2

def index(request):
    context={'text':'Welcome!!'}
    return render(request,'learnapp\index.html',context)

def details(request):
    form1=fm1()
    form2=fm2()
    if request.method=="POST":
        form1=fm1(request.POST)
        form2=fm2(request.POST)

    if form1.is_valid():
        form1.save(commit=True)
    else: print('Error')

    if form2.is_valid():
        form2.save(commit=True)
        return index(request)
    else: print('Error2')

    return render(request,'learnapp\detail.html',{
    'form1':form1,'form2':form2
    })
# Create your views here.

templates/learnapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class='navbar navbar-inverse navbar-static-top'>
      <div class="container">
      <ul class="nav navbar-nav">
      <li><a class="navbar-link" href="{% url 'index' %}">Index</a></li>
      <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
      <li><a class="navbar-link" href="#"></a>Profile</li>
      <li><a class="navbar-link" href="{% url 'learnapp:details' %}">Sign up</a></li>
      </div>
    </nav>
    <div class="container">
      {% block block1 %}
      {<!-- details in the other web pages -->}
      {% endblock %}

    </div>
  </body>
</html>

templates/learnapp/detail.html
<!DOCTYPE html>
{% extends "learnapp\base.html" %}
{% block block1 %}
  <h1> Details here: </h1>
  <div class="container">
    <div class="jumbotron">
      <form method="POST">
        {{form1.as_p}}
        {{form2.as_p}}
        {% csrf_token %}
        <input type="submit" name="Submit" class="btn btn-primary " value="submit">
      </form>
    </div>
  </div>
  {% endblock %}

templates/learnapp/index.html
<!DOCTYPE html>
{% extends "learnapp/base.html" %}

  {% block block1 %}
    {% load staticfiles %}
    <h1>{{text|upper}}</h1>
    <h2>Welcome to home</h2>
    <img src="{% static "images/ecell-logo-bw.png" %}" alt="">
  {% endblock %}